### ISSUE TITLE
Error Opening Jar File : A JNI Error has occurred, please check your installation and try again

### ISSUE THREAD

**Issue by josephAttia** [tfinnm/AcademiesHacks2#1] opened 2021-06-04 00:57 UTC
![error](https://user-images.githubusercontent.com/61055258/120729856-3192f400-c4ae-11eb-8eed-874eb3b0ecc7.jpg)
Attached Above is the Error

System Config:
Windows 10
JDK Version: Latest Release
JRE Version: Latest Release

**Comment by tfinnm** [comment] 2021-06-11 22:07
Howdy joseph, thanks for bringing this up, I have been unable to reproduce this on any of my systems, however I may be able to identify the problem if you could let me know which "brand" of JRE you have installed (ie. Oracle, OpenJDK, etc.) as well as what the output of running `java -version` is.

I have a few suspicions of what might be causing this, and knowing that should allow me to figure it out and fix it.

**Comment by josephAttia** [comment] 2021-06-15 20:39
Below are the specifications:
```
JRE: OpenJDK v9
```
```
java -version: 16.0.1
```
I updated my Java version and my JRE version but still no luck
Have you confirmed you packaged all the required libraries and packages into the jar file?

**Comment by tfinnm** [comment] 2021-06-15 22:42
Thanks for responding, I do see a bit of a conflict of information in this, but I believe I have found the problem. 16.0.1 would imply that you are running OpenJDK v16, but if you also have OpenJDK v9 installed, that may be the problem.

This game was compiled in OpenJDK v11 and targets Java 11 onwards (mainly java 11 and java 16), however, by default java will throw a JNI error anytime a program is run in a JRE version prior to the JDK that compiled it.

To verify that the program itself is working, I have spun up 3 VMs each with a clean windows 10 install, and running java 8, java 11, and java 16 respectively. On each VM, I downloaded the executable of this game from itch.io and in the java 11 and 16 environments, the game ran without problems, however I encountered this error on the java 8 environment, which would suggest that I would see the same behavior on java 9 as well. These results were also verified on Ubuntu 20.04 LTS.

I have found in the past that Java may execute jars in a previous version of the JRE if multiple are installed, depending on how the update was installed, so it may be worth checking this, however that may not be necessary.

In my next release I will be manually overriding the JRE version check as this program was programmed to be backwards compatible all the way to java 8 and is backwards compatible to java 7 or earlier, with the caveat that modding would not be available when using a JRE prior to java 8 and I will be unable to test on versions prior to java 8.

This should hopefully fix your problem, so I will be closing this issue, but if you find something I addressed incorrectly in this assessment, feel free to reopen the issue and let me know.

Also, just as a final side note, I am just now noticing that when you opened this, the released version did have a bug with launching that occurred (to my knowledge) only on the official JRE, but that has since been fixed, so it is also possible that it was a result of that and that it also happened on some versions of the openJDK JRE, but I find this a less likely possibility.

**Comment by josephAttia** [comment] 2021-06-15 23:11
Hey there! 
I've began updating all my Java Runtime Environments to the versions you mentioned in the above comment.
I'll get back to you when that's all cleared up. Hopefully it works, if not I will reopen this issue for further development and support.
 
Would you mind providing me with the link to the itch.io page?

**Comment by josephAttia** [comment] 2021-06-15 23:15
Please disregard my question in my last comment, I found the link!

**Comment by josephAttia** [comment] 2021-08-08 20:29
Can you _**re-open**_ this issue? 

This issue still priests even with a clean windows install.

**Comment by josephAttia** [comment] 2021-08-09 15:27
When running **java -version** I get:

`
java version "1.8.0_301"
`
`
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
`
`
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)
`

JRE:
`
OpenJDK
`

Hope this information helps in debugging the problem.

Question:
Are you sure that you included all the libraries and packages when building the JAR file?

**Closed as completed** 2021-08-19 15:44 UTC
Labels: fix pending release
